name: Terraform Release

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '.github/workflows/terraform-release.yml'
      # Don't trigger on README updates from terraform-docs
      - '!README.md'
    tags-ignore:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      force_version:
        description: 'Force specific version (leave empty for auto versioning)'
        required: false
        default: ''
        type: string
      dry_run:
        description: 'Dry run (no actual release)'
        required: false
        default: false
        type: boolean

jobs:
  release:
    name: Create Terraform Release
    uses: proscia-techops/github-actions-workflows/.github/workflows/terraform-release.yml@main
    with:
      working-directory: '.'
      force_version: ${{ github.event.inputs.force_version || '' }}
      dry_run: ${{ fromJSON(github.event.inputs.dry_run || 'false') }}
      # The centralized workflow automatically handles semantic versioning:
      # - Commits with "feat!" or "BREAKING CHANGE" in title/body will trigger major bump
      # - Commits with "feat" type will trigger minor bump
      # - Commits with "fix" type will trigger patch bump