name: Terraform Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Terraform Tests
    uses: proscia-techops/github-actions-workflows/.github/workflows/terraform-test-null.yml@main
