name: Terraform Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Terraform Tests
    uses: proscia-techops/github-actions-workflows/.github/workflows/terraform-test.yml@main
    with:
      working-directory: '.'
      provider: 'none'
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
