name: Terraform Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-lint:
    name: Terraform Compliance
    uses: proscia-techops/github-actions-workflows/.github/workflows/terraform-lint.yml@main
    with:
      working-directory: '.'
      fail-on-violations: true