name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trivy-scan:
    name: Trivy Security Scan
    uses: proscia-techops/github-actions-workflows/.github/workflows/terraform-trivy.yml@main
    with:
      working-directory: '.'
      config-file: '.trivy.yaml'
      sarif-upload: true
      fail-on-severity: 'MEDIUM'
      terraform-version: 'latest'
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    permissions:
      contents: read
      security-events: write
      pull-requests: write